version: "3.8"
services:

  passken-express:
    build: ./
    container_name: passken-express
    volumes:
      - ./:/usr/src/app
      - passken-express_node_modules:/usr/src/app/node_modules


volumes:
  passken-express_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules